### GET request to example server
GET http://localhost:8000/game

> {%
    client.global.set("player_name", response.body.current_player.name);
    client.global.set("move", JSON.stringify(response.body.possible_moves[0]));
%}

###

POST http://localhost:8000/move
Content-Type: application/json

{
    "combination": {{combination}},
    "player_name": "{{player_name}}"
}
